version: "3"
services:
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:mysql://mysqldb:3306/pousada
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=12345
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "pousada"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "12345"

volumes:
  mysql-data:
    external: false